version: '3.9'
services:
  client:
    build: ./react/chat-room-frontend
    ports: 
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "3123:3123"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo/chat-room
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
